abstract class AppStates {}
class InitialAppState extends AppStates{}
class BNBChangeCurrentIndex extends AppStates{}
class FABChange extends AppStates{}
class Loading extends AppStates{}
class DataCreate extends AppStates{}
class DataInsert extends AppStates{}
class DataGet extends AppStates{}
class DataDelete extends AppStates{}